# docker-compose.yml
 
# Reference compose file version 3
version: “3”
services:
# Service name is react-app
  store-manager-web:
    image: node:18-alpine
  # build from Dockerfile
    build: .
  # expose 3000 as hosting port & 3000 in container port
    ports:
      - "8002:8002"
    command: npm run dev -- --port 8002 --host 0.0.0.0
